//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.DictionaryBuilder v8.0.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Umbraco.Web.PublishedModels
{
    public partial class Dictionaries
    {
        public partial class _Test
        {
            public partial class _Child
            {
                private static _ChildValue _childValue = new _ChildValue();

                /// <summary>
                /// The dictionary item: [Child.Value]
                /// </summary>
                [System.CodeDom.Compiler.GeneratedCode("Umbraco.DictionaryBuilder", "8.0.0")]
                public _ChildValue ChildValue => _childValue;

                [Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryKey("Child.Value")]
                public partial class _ChildValue : Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryItem { }
            }
        }
    }
}
