//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.DictionaryBuilder v8.0.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Umbraco.Web.PublishedModels
{
    public partial class Dictionaries
    {
        public partial class _Test
        {
            private static _Child _child = new _Child();

            /// <summary>
            /// The dictionary item: [Child]
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCode("Umbraco.DictionaryBuilder", "8.0.0")]
            public _Child Child => _child;

            [Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryKey("Child")]
            public partial class _Child : Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryItem { }
        }
    }
}
