//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.DictionaryBuilder v8.0.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Umbraco.Web.PublishedModels
{
    public partial class Dictionaries
    {
        public partial class _Morten
        {
            private static _Fredsgaard _fredsgaard = new _Fredsgaard();

            /// <summary>
            /// The dictionary item: [Fredsgaard]
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCode("Umbraco.DictionaryBuilder", "8.0.0")]
            public _Fredsgaard Fredsgaard => _fredsgaard;

            [Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryKey("Fredsgaard")]
            public partial class _Fredsgaard : Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryItem { }
        }
    }
}
