//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.DictionaryBuilder v8.0.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Umbraco.Web.PublishedModels
{
    public partial class Dictionaries
    {
        private static _Morten _morten = new _Morten();

        /// <summary>
        /// The dictionary item: [Morten]
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Umbraco.DictionaryBuilder", "8.0.0")]
        public static _Morten Morten => _morten;

        [Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryKey("Morten")]
        public partial class _Morten : Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryItem { }
    }
}
