//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.DictionaryBuilder v8.0.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Umbraco.Web.PublishedModels
{
    public partial class Dictionaries
    {
        private static _Morten2 _morten2 = new _Morten2();

        /// <summary>
        /// The dictionary item: [Morten2]
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Umbraco.DictionaryBuilder", "8.0.0")]
        public static _Morten2 Morten2 => _morten2;

        [Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryKey("Morten2")]
        public partial class _Morten2 : Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryItem { }
    }
}
