//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.DictionaryBuilder v8.0.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Umbraco.Web.PublishedModels
{
    public partial class Dictionaries
    {
        public partial class _Morten
        {
            public partial class _Fredsgaard
            {
                private static _Pedersen _pedersen = new _Pedersen();

                /// <summary>
                /// The dictionary item: [Pedersen]
                /// </summary>
                [System.CodeDom.Compiler.GeneratedCode("Umbraco.DictionaryBuilder", "8.0.0")]
                public _Pedersen Pedersen => _pedersen;

                [Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryKey("Pedersen")]
                public partial class _Pedersen : Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryItem { }
            }
        }
    }
}
