//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.DictionaryBuilder v8.0.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Umbraco.Web.PublishedModels
{
    public partial class Dictionaries
    {
        private static _Test2 _test2 = new _Test2();

        /// <summary>
        /// The dictionary item: [Test2]
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Umbraco.DictionaryBuilder", "8.0.0")]
        public static _Test2 Test2 => _test2;

        [Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryKey("Test2")]
        public partial class _Test2 : Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryItem { }
    }
}
