//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.DictionaryBuilder v8.0.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Umbraco.Web.PublishedModels
{
    public partial class Dictionaries
    {
        private static _Test3 _test3 = new _Test3();

        /// <summary>
        /// The dictionary item: [Test3]
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Umbraco.DictionaryBuilder", "8.0.0")]
        public static _Test3 Test3 => _test3;

        [Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryKey("Test3")]
        public partial class _Test3 : Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryItem { }
    }
}
