//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.DictionaryBuilder v8.0.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Umbraco.Web.PublishedModels
{
    public partial class Dictionaries
    {
        private static _Test _test = new _Test();

        /// <summary>
        /// The dictionary item: [Test]
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Umbraco.DictionaryBuilder", "8.0.0")]
        public static _Test Test => _test;

        [Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryKey("Test")]
        public partial class _Test : Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryItem { }
    }
}
