//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.DictionaryBuilder v8.0.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Umbraco.Web.PublishedModels
{
    public partial class Dictionaries
    {
        public partial class _Test
        {
            private static _Value2 _value2 = new _Value2();

            /// <summary>
            /// The dictionary item: [Value2]
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCode("Umbraco.DictionaryBuilder", "8.0.0")]
            public _Value2 Value2 => _value2;

            [Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryKey("Value2")]
            public partial class _Value2 : Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryItem { }
        }
    }
}
