//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.DictionaryBuilder v8.0.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Umbraco.Web.PublishedModels
{
    public partial class Dictionaries
    {
        public partial class _Test
        {
            private static _Value _value = new _Value();

            /// <summary>
            /// The dictionary item: [Value]
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCode("Umbraco.DictionaryBuilder", "8.0.0")]
            public _Value Value => _value;

            [Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryKey("Value")]
            public partial class _Value : Umbraco.ModelsBuilder.Embedded.Dictionary.DictionaryItem { }
        }
    }
}
