//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.DictionaryBuilder v1.0.2
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.Web
{
    public partial class Dictionaries
    {
        #region Child
        public partial class _Test
        {
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
            private static _Child _child = new _Child();

            /// <summary>
            /// The dictionary item: [Child]
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
            public _Child Child => _child;

            public partial class _Child : Umbraco.DictionaryBuilder.Models.DictionaryModel
            {
                public _Child() : base("Child") {}
            }
        }
        #endregion

        #region Child.Value
        public partial class _Test
        {
            public partial class _Child
            {
                [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
                private static _Value _value = new _Value();

                /// <summary>
                /// The dictionary item: [Child.Value]
                /// </summary>
                [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
                public _Value Value => _value;

                public partial class _Value : Umbraco.DictionaryBuilder.Models.DictionaryModel
                {
                    public _Value() : base("Child.Value") {}
                }
            }
        }
        #endregion

        #region Morten
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
        private static _Morten _morten = new _Morten();

        /// <summary>
        /// The dictionary item: [Morten]
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
        public static _Morten Morten => _morten;

        public partial class _Morten : Umbraco.DictionaryBuilder.Models.DictionaryModel
        {
            public _Morten() : base("Morten") {}
        }
        #endregion

        #region Morten.Fredsgaard
        public partial class _Morten
        {
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
            private static _Fredsgaard _fredsgaard = new _Fredsgaard();

            /// <summary>
            /// The dictionary item: [Morten.Fredsgaard]
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
            public _Fredsgaard Fredsgaard => _fredsgaard;

            public partial class _Fredsgaard : Umbraco.DictionaryBuilder.Models.DictionaryModel
            {
                public _Fredsgaard() : base("Morten.Fredsgaard") {}
            }
        }
        #endregion

        #region Morten.Fredsgaard.Pedersen
        public partial class _Morten
        {
            public partial class _Fredsgaard
            {
                [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
                private static _Pedersen _pedersen = new _Pedersen();

                /// <summary>
                /// The dictionary item: [Morten.Fredsgaard.Pedersen]
                /// </summary>
                [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
                public _Pedersen Pedersen => _pedersen;

                public partial class _Pedersen : Umbraco.DictionaryBuilder.Models.DictionaryModel
                {
                    public _Pedersen() : base("Morten.Fredsgaard.Pedersen") {}
                }
            }
        }
        #endregion

        #region Morten.Test
        public partial class _Morten
        {
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
            private static _Test _test = new _Test();

            /// <summary>
            /// The dictionary item: [Morten.Test]
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
            public _Test Test => _test;

            public partial class _Test : Umbraco.DictionaryBuilder.Models.DictionaryModel
            {
                public _Test() : base("Morten.Test") {}
            }
        }
        #endregion

        #region Morten2
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
        private static _Morten2 _morten2 = new _Morten2();

        /// <summary>
        /// The dictionary item: [Morten2]
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
        public static _Morten2 Morten2 => _morten2;

        public partial class _Morten2 : Umbraco.DictionaryBuilder.Models.DictionaryModel
        {
            public _Morten2() : base("Morten2") {}
        }
        #endregion

        #region Morten2.Hund
        public partial class _Morten2
        {
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
            private static _Hund _hund = new _Hund();

            /// <summary>
            /// The dictionary item: [Morten2.Hund]
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
            public _Hund Hund => _hund;

            public partial class _Hund : Umbraco.DictionaryBuilder.Models.DictionaryModel
            {
                public _Hund() : base("Morten2.Hund") {}
            }
        }
        #endregion

        #region Settings
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
        private static _Settings _settings = new _Settings();

        /// <summary>
        /// The dictionary item: [Settings]
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
        public static _Settings Settings => _settings;

        public partial class _Settings : Umbraco.DictionaryBuilder.Models.DictionaryModel
        {
            public _Settings() : base("Settings") {}
        }
        #endregion

        #region Settings.DateTime
        public partial class _Settings
        {
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
            private static _DateTime _dateTime = new _DateTime();

            /// <summary>
            /// The dictionary item: [Settings.DateTime]
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
            public _DateTime DateTime => _dateTime;

            public partial class _DateTime : Umbraco.DictionaryBuilder.Models.DictionaryModel
            {
                public _DateTime() : base("Settings.DateTime") {}
            }
        }
        #endregion

        #region Settings.DateTime.Months
        public partial class _Settings
        {
            public partial class _DateTime
            {
                [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
                private static _Months _months = new _Months();

                /// <summary>
                /// The dictionary item: [Settings.DateTime.Months]
                /// </summary>
                [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
                public _Months Months => _months;

                public partial class _Months : Umbraco.DictionaryBuilder.Models.DictionaryModel
                {
                    public _Months() : base("Settings.DateTime.Months") {}
                }
            }
        }
        #endregion

        #region Test
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
        private static _Test _test = new _Test();

        /// <summary>
        /// The dictionary item: [Test]
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
        public static _Test Test => _test;

        public partial class _Test : Umbraco.DictionaryBuilder.Models.DictionaryModel
        {
            public _Test() : base("Test") {}
        }
        #endregion

        #region Test2
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
        private static _Test2 _test2 = new _Test2();

        /// <summary>
        /// The dictionary item: [Test2]
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
        public static _Test2 Test2 => _test2;

        public partial class _Test2 : Umbraco.DictionaryBuilder.Models.DictionaryModel
        {
            public _Test2() : base("Test2") {}
        }
        #endregion

        #region Test3
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
        private static _Test3 _test3 = new _Test3();

        /// <summary>
        /// The dictionary item: [Test3]
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
        public static _Test3 Test3 => _test3;

        public partial class _Test3 : Umbraco.DictionaryBuilder.Models.DictionaryModel
        {
            public _Test3() : base("Test3") {}
        }
        #endregion

        #region Value
        public partial class _Test
        {
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
            private static _Value _value = new _Value();

            /// <summary>
            /// The dictionary item: [Value]
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
            public _Value Value => _value;

            public partial class _Value : Umbraco.DictionaryBuilder.Models.DictionaryModel
            {
                public _Value() : base("Value") {}
            }
        }
        #endregion

        #region Value2
        public partial class _Test
        {
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
            private static _Value2 _value2 = new _Value2();

            /// <summary>
            /// The dictionary item: [Value2]
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.DictionaryBuilder", "1.0.2")]
            public _Value2 Value2 => _value2;

            public partial class _Value2 : Umbraco.DictionaryBuilder.Models.DictionaryModel
            {
                public _Value2() : base("Value2") {}
            }
        }
        #endregion
    }
}
